insert into BRANCHES (location,name,phone) values ('washington dc','community center','8527410369');
insert into BRANCHES (location,name,phone) values ('delhi','aimms','0021457896');
insert into BRANCHES (location,name,phone) values ('paris','government center','8574120369');
insert into BRANCHES (location,name,phone) values ('petersburg',' ru hospital','8574963210');
insert into BRANCHES (location,name,phone) values ('seoul','social center','1425703968');
insert into BRANCHES (location,name,phone) values ('london','queen hospital','9857462144');
insert into BRANCHES (location,name,phone) values ('tokiyo','hiroshima community','9685743210');
insert into BRANCHES (location,name,phone) values ('Canbera','kangarro center','5896741230');
insert into BRANCHES (location,name,phone) values ('jakarta','medical facility','2350147680');
insert into BRANCHES (location,name,phone) values ('berlin','government hospital','3597410688');
insert into VACCINES (name,type) values ('pfizer','injection');
insert into VACCINES (name,type) values ('covid shield','injection');
insert into VACCINES (name,type) values ('polio','injection');
insert into VACCINES (name,type) values ('polio','oral');
insert into VACCINES (name,type) values ('hapatitus A','injection');
insert into VACCINES (name,type) values ('hapatitus A','oral');
insert into VACCINES (name,type) values ('hapatitus B','injection');
insert into VACCINES (name,type) values ('hapatitus C','injection');
insert into VACCINES (name,type) values ('titnus','injection');
insert into VACCINES (name,type) values ('tuberculosis','injection');
insert into VACCINES (name,type) values ('typhiod','injection');
insert into VACCINES (name,type) values ('hiv','injection');
insert into VACCINES (name,type) values ('bcg','injection');
insert into VACCINES (name,type) values ('covid shield','oral');
insert into VACCINES (name,type) values ('bcg','oral');
insert into VACCINES (name,type) values ('chicken pox','oral');
insert into VACCINES (name,type) values ('smallpox','oral');
insert into VACCINES (name,type) values ('yellow fever','oral');
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (100,1,1);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (500,1,18);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (0,1,3);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (10,1,17);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (145,1,5);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (589,1,6);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (33,1,7);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (1,1,8);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (0,1,9);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (522,1,10);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (3,1,11);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (859,1,12);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (100,1,13);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (100,1,14);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (100,1,15);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (10,2,1);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (10,2,11);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (1,2,3);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (1,2,14);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (1,2,5);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (22,2,6);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (58,2,7);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (10,2,8);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (3,2,18);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (2,3,1);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (5,2,13);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (2,3,18);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (2,3,14);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (2,3,16);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (5,2,15);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (6,5,14);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (1,7,13);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (1,8,12);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (1,9,12);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (1,4,1);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (88,5,15);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (55,6,15);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (7,8,15);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (77,10,15);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (9,4,15);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (65,4,18);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (45,4,9);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (411,4,16);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (100,4,14);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (25,4,13);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (25,5,11);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (25,6,12);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (23,6,3);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (59,8,11);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (68,8,3);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (31,7,12);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (31,9,15);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (122,6,6);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (999,5,6);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (145,5,5);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (0,5,18);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (0,4,5);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (0,2,12);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (0,3,10);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (2,7,1);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (2,7,3);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (5,8,8);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (5,9,4);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (5,10,10);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (5,10,3);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (5,10,7);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (5,10,9);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (5,10,12);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (45,10,13);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (16,10,18);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (12,8,18);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (12,9,18);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (24,3,17);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (24,4,17);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (78,3,6);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (41,2,17);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (10,5,3);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (20,8,7);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (20,7,7);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (02,4,4);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (20,6,14);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (20,4,12);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (20,4,3);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (20,4,2);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (20,4,10);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (20,5,10);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (23,6,10);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (23,6,1);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (32,8,10);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (23,9,10);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (35,7,10);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (568,9,2);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (885,7,16);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (85,7,11);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (8,7,17);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (98,8,16);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (89,8,17);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (89,5,17);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (89,5,1);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (56,5,12);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (56,5,13);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (69,5,16);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (68,6,16);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (47,8,1);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (77,9,17);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (100,7,9);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (100,10,1);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (100,10,16);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (100,10,14);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (100,10,17);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (100,10,2);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (100,10,4);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (100,10,5);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (100,10,6);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (100,10,8);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (100,9,3);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (100,9,1);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (100,9,7);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (100,9,8);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (100,9,9);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (100,9,11);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (100,9,13);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (100,3,8);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (100,3,9);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (100,3,7);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (100,3,11);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (100,3,12);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (100,3,13);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (100,4,8);
insert into VACCINES_BRANCHES (quantity, branch_branch_id, vaccine_vaccine_id) values (100,4,11);
insert into AVAILABILITY (branch_branch_id, dates, slot) values (5,'2021-03-16','09:00-09:15');
insert into AVAILABILITY (branch_branch_id, dates, slot) values (5,'2021-03-16','09:30-09:45');
insert into AVAILABILITY (branch_branch_id, dates, slot) values (5,'2021-03-16','10:00-10:15');
insert into AVAILABILITY (branch_branch_id, dates, slot) values (5,'2021-03-16','11:15-11:30');
insert into AVAILABILITY (branch_branch_id, dates, slot) values (5,'2021-03-16','11:30-11:45');
insert into AVAILABILITY (branch_branch_id, dates, slot) values (5,'2021-03-16','14:00-14:15');
insert into AVAILABILITY (branch_branch_id, dates, slot) values (5,'2021-03-18','09:00-09:15');
insert into AVAILABILITY (branch_branch_id, dates, slot) values (5,'2021-03-18','09:15-09:30');
insert into AVAILABILITY (branch_branch_id, dates, slot) values (5,'2021-03-19','15:00-15:15');
insert into AVAILABILITY (branch_branch_id, dates, slot) values (2,'2021-03-19','15:30-15:45');
insert into AVAILABILITY (branch_branch_id, dates, slot) values (2,'2021-03-19','16:00-16:15');
insert into AVAILABILITY (branch_branch_id, dates, slot) values (2,'2021-03-20','09:00-09:15');
insert into AVAILABILITY (branch_branch_id, dates, slot) values (2,'2021-02-20','09:15-09:30');
insert into AVAILABILITY (branch_branch_id, dates, slot) values (5,'2021-03-20','09:30-09:45');
insert into AVAILABILITY (branch_branch_id, dates, slot) values (1,'2021-03-28','09:45-10:00');
insert into AVAILABILITY (branch_branch_id, dates, slot) values (2,'2021-03-28','12:00-12:15');
insert into AVAILABILITY (branch_branch_id, dates, slot) values (6,'2021-03-28','12:30-12:45');
insert into AVAILABILITY (branch_branch_id, dates, slot) values (7,'2021-03-28','12:45-13:00');
insert into AVAILABILITY (branch_branch_id, dates, slot) values (8,'2021-03-28','14:00-14:15');
insert into AVAILABILITY (branch_branch_id, dates, slot) values (9,'2021-03-28','15:00-15:15');
insert into AVAILABILITY (branch_branch_id, dates, slot) values (9,'2021-03-28','15:15-15:30');
insert into AVAILABILITY (branch_branch_id, dates, slot) values (5,'2021-03-28','16:45-17:00');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP,AMOUNT, NAME, EMAIL,STATUS) values (5,3,'CASH','2021-03-10',100,'rohit','rohit@yopmail.com','COMPLETED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP,AMOUNT, NAME, EMAIL,STATUS) values (5,2,'CASH','2021-03-09',1500.22,'lenovo','lenovo@yopmail.com','COMPLETED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP,AMOUNT, NAME, EMAIL,STATUS) values (5,3,'CASH','2021-03-08',100,'asd','asd@yopmail.com','COMPLETED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP,AMOUNT, NAME, EMAIL,STATUS) values (2,4,'CASH','2021-03-07',15,'son','son@yopmail.com','COMPLETED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP,AMOUNT, NAME, EMAIL,STATUS) values (2,5,'CASH','2021-03-06',55.50,'saab','saab@yopmail.com','COMPLETED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP,AMOUNT, NAME, EMAIL,STATUS) values (2,6,'CASH','2021-03-05',908.22,'gripen','gripen@yopmail.com','COMPLETED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP,AMOUNT, NAME, EMAIL,STATUS) values (5,7,'CASH','2021-03-04',77,'miraz','miraz@yopmail.com','COMPLETED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP,AMOUNT, NAME, EMAIL,STATUS) values (5,12,'CASH','2021-03-10',100,'f','f@yopmail.com','COMPLETED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP,AMOUNT, NAME, EMAIL,STATUS) values (1,13,'CASH','2021-03-10',150,'boieng','boieng@yopmail.com','COMPLETED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP,AMOUNT, NAME, EMAIL,STATUS) values (1,11,'CASH','2021-03-08',13,'buster','buster@yopmail.com','COMPLETED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP,AMOUNT, NAME, EMAIL,STATUS) values (7,1,'CASH','2021-03-08',12,'data','data@yopmail.com','COMPLETED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP,AMOUNT, NAME, EMAIL,STATUS) values (2,3,'CASH','2021-02-08',908.22,'data','data@yopmail.com','COMPLETED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP,AMOUNT, NAME, EMAIL,STATUS) values (2,3,'CASH','2021-03-08',908.22,'siera','siera@yopmail.com','COMPLETED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP,AMOUNT, NAME, EMAIL,STATUS) values (8,3,'CASH','2021-03-20',100,'rohit','rohit@yopmail.com','SCHEDULED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP,AMOUNT, NAME, EMAIL,STATUS) values (8,2,'CASH','2021-03-22',1500.22,'lenovo','lenovo@yopmail.com','SCHEDULED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP,AMOUNT, NAME, EMAIL,STATUS) values (8,16,'CASH','2021-03-23',100,'asd','asd@yopmail.com','SCHEDULED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP,AMOUNT, NAME, EMAIL,STATUS) values (8,4,'CASH','2021-03-20',15,'son','son@yopmail.com','SCHEDULED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP,AMOUNT, NAME, EMAIL,STATUS) values (1,5,'CASH','2021-03-22',55.50,'saab','saab@yopmail.com','SCHEDULED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP,AMOUNT, NAME, EMAIL,STATUS) values (1,6,'CASH','2021-03-21',908.22,'gripen','gripen@yopmail.com','SCHEDULED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP,AMOUNT, NAME, EMAIL,STATUS) values (1,7,'CASH','2021-03-29',77,'miraz','miraz@yopmail.com','SCHEDULED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP,AMOUNT, NAME, EMAIL,STATUS) values (1,12,'CASH','2021-03-29',100,'f','f@yopmail.com','SCHEDULED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP,AMOUNT, NAME, EMAIL,STATUS) values (1,13,'CASH','2021-03-23',150,'boieng','boieng@yopmail.com','SCHEDULED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP,AMOUNT, NAME, EMAIL,STATUS) values (3,11,'CASH','2021-03-25',13,'buster','buster@yopmail.com','SCHEDULED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP,AMOUNT, NAME, EMAIL,STATUS) values (4,15,'CASH','2021-03-27',12,'data','data@yopmail.com','SCHEDULED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP,AMOUNT, NAME, EMAIL,STATUS) values (5,18,'CASH','2021-03-27',908.22,'data','data@yopmail.com','SCHEDULED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP,AMOUNT, NAME, EMAIL,STATUS) values (9,17,'CASH','2021-03-27',908.22,'siera','siera@yopmail.com','SCHEDULED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP, CREDIT_CARD_NUMBER, CVV , AMOUNT, EXPIRY, NAME, EMAIL, STATUS) values (9,17,'CREDIT','2021-03-05',4111411141114111,345,908.22,03-22,'random','random@yopmail.com','COMPLETED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP, CREDIT_CARD_NUMBER, CVV , AMOUNT, EXPIRY, NAME, EMAIL, STATUS) values (7,18,'CREDIT','2021-03-05',4111111111111111,345,908.22,03-22,'fast','fast@yopmail.com','COMPLETED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP, CREDIT_CARD_NUMBER, CVV , AMOUNT, EXPIRY, NAME, EMAIL, STATUS) values (6,16,'CREDIT','2021-03-05',4111111111111111,345,908.22,03-22,'slow','slow@yopmail.com','COMPLETED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP, CREDIT_CARD_NUMBER, CVV , AMOUNT, EXPIRY, NAME, EMAIL, STATUS) values (4,01,'CREDIT','2021-03-02',4111111111111111,345,908.22,03-22,'yeild','yeild@yopmail.com','COMPLETED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP, CREDIT_CARD_NUMBER, CVV , AMOUNT, EXPIRY, NAME, EMAIL, STATUS) values (4,03,'CREDIT','2021-03-02',4111411141114111,345,908.22,03-22,'strato','strato@yopmail.com','COMPLETED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP, CREDIT_CARD_NUMBER, CVV , AMOUNT, EXPIRY, NAME, EMAIL, STATUS) values (4,13,'CREDIT','2021-03-02',4242424242424242,345,908.22,03-22,'naag','naag@yopmail.com','COMPLETED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP, CREDIT_CARD_NUMBER, CVV , AMOUNT, EXPIRY, NAME, EMAIL, STATUS) values (4,14,'CREDIT','2021-03-02',4111111111111111,345,908.22,03-22,'can','can@yopmail.com','COMPLETED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP, CREDIT_CARD_NUMBER, CVV , AMOUNT, EXPIRY, NAME, EMAIL, STATUS) values (7,15,'CREDIT','2021-03-02',4111411141114111,345,908.22,03-22,'cannot','cannot@yopmail.com','COMPLETED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP, CREDIT_CARD_NUMBER, CVV , AMOUNT, EXPIRY, NAME, EMAIL, STATUS) values (6,01,'CREDIT','2021-03-26',4111411141114111,345,908.22,03-22,'submerged','submerged@yopmail.com','SCHEDULED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP, CREDIT_CARD_NUMBER, CVV , AMOUNT, EXPIRY, NAME, EMAIL, STATUS) values (6,4,'CREDIT','2021-03-26',4242424242424242,345,908.22,03-22,'rain','rain@yopmail.com','SCHEDULED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP, CREDIT_CARD_NUMBER, CVV , AMOUNT, EXPIRY, NAME, EMAIL, STATUS) values (6,5,'CREDIT','2021-03-26',4242424242424242,345,908.22,03-22,'red','red@yopmail.com','SCHEDULED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP, CREDIT_CARD_NUMBER, CVV , AMOUNT, EXPIRY, NAME, EMAIL, STATUS) values (6,6,'CREDIT','2021-03-25',4242424242424242,345,908.22,03-22,'dark','dark@yopmail.com','SCHEDULED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP, CREDIT_CARD_NUMBER, CVV , AMOUNT, EXPIRY, NAME, EMAIL, STATUS) values (6,7,'CREDIT','2021-03-25',4111411141114111,345,908.22,03-22,'random','random@yopmail.com','SCHEDULED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP, CREDIT_CARD_NUMBER, CVV , AMOUNT, EXPIRY, NAME, EMAIL, STATUS) values (6,8,'CREDIT','2021-03-25',4111411141114111,345,908.22,03-22,'random','random@yopmail.com','SCHEDULED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP, CREDIT_CARD_NUMBER, CVV , AMOUNT, EXPIRY, NAME, EMAIL, STATUS) values (6,12,'CREDIT','2021-03-22',4242424242424242,345,908.22,03-22,'random','random@yopmail.com','SCHEDULED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP, CREDIT_CARD_NUMBER, CVV , AMOUNT, EXPIRY, NAME, EMAIL, STATUS) values (6,13,'CREDIT','2021-03-22',4111111111111111,345,908.22,03-22,'random','random@yopmail.com','SCHEDULED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP,PAYMENT_METHOD_ID,AMOUNT, NAME, EMAIL, STATUS) values (8,1,'FAWRY','2021-03-14','ras348hs@fawry',908.22,'random','random@yopmail.com','COMPLETED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP,PAYMENT_METHOD_ID,AMOUNT, NAME, EMAIL, STATUS) values (8,3,'FAWRY','2021-03-14','fde4f@fawry',908.22,'random','random@yopmail.com','COMPLETED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP,PAYMENT_METHOD_ID,AMOUNT, NAME, EMAIL, STATUS) values (8,4,'FAWRY','2021-03-14','2e3e@fawry',908.22,'random','random@yopmail.com','COMPLETED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP,PAYMENT_METHOD_ID,AMOUNT, NAME, EMAIL, STATUS) values (8,5,'FAWRY','2021-03-15','345fe@fawry',908.22,'random','random@yopmail.com','COMPLETED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP,PAYMENT_METHOD_ID,AMOUNT, NAME, EMAIL, STATUS) values (8,6,'FAWRY','2021-03-13','3r3re@fawry',908.22,'random','random@yopmail.com','COMPLETED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP,PAYMENT_METHOD_ID,AMOUNT, NAME, EMAIL, STATUS) values (8,7,'FAWRY','2021-03-13','5t5g5@fawry',908.22,'random','random@yopmail.com','COMPLETED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP,PAYMENT_METHOD_ID,AMOUNT, NAME, EMAIL, STATUS) values (8,8,'FAWRY','2021-03-13','1w2wd@fawry',908.22,'random','random@yopmail.com','COMPLETED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP,PAYMENT_METHOD_ID,AMOUNT, NAME, EMAIL, STATUS) values (3,9,'FAWRY','2021-03-13','3r43@fawry',908.22,'random','random@yopmail.com','COMPLETED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP,PAYMENT_METHOD_ID,AMOUNT, NAME, EMAIL, STATUS) values (3,10,'FAWRY','2021-04-01','ras348hs@fawry',908.22,'random','random@yopmail.com','SCHEDULED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP,PAYMENT_METHOD_ID,AMOUNT, NAME, EMAIL, STATUS) values (8,11,'FAWRY','2021-04-28','ras348hs@fawry',908.22,'random','random@yopmail.com','SCHEDULED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP,PAYMENT_METHOD_ID,AMOUNT, NAME, EMAIL, STATUS) values (8,12,'FAWRY','2021-04-07','f4f4@fawry',908.22,'random','random@yopmail.com','SCHEDULED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP,PAYMENT_METHOD_ID,AMOUNT, NAME, EMAIL, STATUS) values (8,13,'FAWRY','2021-04-05','rasdw3@fawry',908.22,'random','random@yopmail.com','SCHEDULED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP,PAYMENT_METHOD_ID,AMOUNT, NAME, EMAIL, STATUS) values (8,14,'FAWRY','2021-04-07','7u7juj@fawry',908.22,'random','random@yopmail.com','SCHEDULED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP,PAYMENT_METHOD_ID,AMOUNT, NAME, EMAIL, STATUS) values (8,15,'FAWRY','2021-04-07','ras348hs@fawry',908.22,'random','random@yopmail.com','SCHEDULED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP,PAYMENT_METHOD_ID,AMOUNT, NAME, EMAIL, STATUS) values (8,16,'FAWRY','2021-04-05','44r@fawry',908.22,'random','random@yopmail.com','SCHEDULED');
insert into BOOKINGS (BRANCH_BRANCH_ID,VACCINE_VACCINE_ID,PAYMENT_TYPE,TIMESTAMP,PAYMENT_METHOD_ID,AMOUNT, NAME, EMAIL, STATUS) values (3,17,'FAWRY','2021-04-02','5trr@fawry',908.22,'random','random@yopmail.com','SCHEDULED');